package program5;
/*Will Ence 
 * 9/10
 * ascii art examples
 */

public class Ascii1 {

	public static void main(String[] args) {
		//print the statement "HI"
		System.out.println("HH  HH\tIIIIII");
		System.out.println("HH  HH\t  II  ");
		System.out.println("HHHHHH\t  II  ");
		System.out.println("HH  HH\t  II  ");
		System.out.println("HH  HH\tIIIIII");
		
		
		//print a guy riding a bicycle
		System.out.println("--------  __@");
		System.out.println("-----  _'\\<,_");
		System.out.println("----  (*)/  (*)");
		System.out.println("~~~~~~~~~~~~~~~~~~~~~~");
		
		
		//print a penguin
		System.out.println(" ___");
		System.out.println("(  0>");
		System.out.println("///\\");
		System.out.println("\\v_/_\n");
		
		//print the "Destiny Hunter Symbol"
		System.out.println("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKXXKKK0KKK00KKXXXKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKKKK0KKXK0KXXXXK0KXXK0KKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0KXXXXXXNX0KKO0XXKKXX0OKK0XNXXXXXKK00KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXX00XXXK0000Oddk00000000kddO0000KXXX00XXKKKKXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXKKKKKXXXXXKkxO0000KKOxdkXNXNNNNXkdxkKK0000OxkKXXXXXXKK0KXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXKKK0KNXX00000kxKNNNXkxKXxxKNXXXKxxXKxkXNXNKxk00000KXXK00KKXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXKKKXXXKOOOO0KXXXXOd0NKxxKNXXkxKNNKxkXXXKxkKX0dOXXNXK0OOOOKXXXKKXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXKKXXNXK0kdkXXXXXXXX0xkxkXNXXNXOxkkxOXXNNNXkxkxOXXXXXXXXkdk0KXXXXKKXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXKK0KKKKOkkkOkodkOOOOOOOo'':cccccc:;'';:cccc:c:,'oOOOOOOOkookOkkkOKKKK0KKXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXNXXNXKKXXXXKOOKXXXXKxxKXXXXXO;. ..  .  .:xx:. ...    .:OXXXXXKxxKXXXXKOOKXXXXKKXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXKKXXXX0O0XXXXXXXXkxKNXXO;..........;xOOx;..........;ONXXKxkXNXXXXXX0k0XXXXKKXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXKKXXXKOOXXXXXXXXXNXkx0Xk,..........ckOOOOkl. ........,kN0xOXXXXXXXXXXXOOKXXXKKXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXKXXXX0k0XXXXXXXXXXNXXOdo'.. ....  .dKXXXXXXXd...... ...'odOXXXXXXXXXXXXX0k0XXXKKXXXXXXXXXX\r\n" + 
				"XXXXXXXXXKXXXX0kKNXXXXXXXXXXXXXKl.. ...... .;xOOOOOOOOx;...... ....lXXXXXXXXXXXXXXXKk0XXXXKKXXXXXXXX\r\n" + 
				"XXXXXNXXKKXXX0kKNXXXXXXXXXXXXXKl..........,xkdOXXXXNXOdkx,........ .lKNXXXXXXXXXXXXXKk0XXXKKXXXXXXXX\r\n" + 
				"XXXXXXXKKXXN0kKNXXXXXXXXXXNXX0c. . ......;OXN0dOXXXXOx0NXO;..........cKXXXXXXXXXXXXXNKk0XXXKKXXXXXXX\r\n" + 
				"XXXXXXKKXXNKk0XXXXXXXXXXXXXX0:..... ....:0XXNXKxkXKkxKXXXX0:..........:0XXXXXXXXXXXXXX0kKNXXKKXXXXXX\r\n" + 
				"XXXXXK0KKKKkxOOOOOOOOOOOOOOx;..........,dkkkkkkxc::lxkkkkkkd,..........;xOOOOOOOOOOOOOOxkKKK00KXXXXX\r\n" + 
				"XXXXXK0KKKOxk0OOOOOOOOOOOOo:dkkxlokkk:..........'::'..........:kkkolxkOd:lOOOOOOOOOOOO0kxOKKK0KXXXXX\r\n" + 
				"XXXXXKKXXN0kXNXXXXXXXXXXXk:dXNXxxXNKo. ........'xXXx'........ .oKXXxxXNXd:kXXXXXXXXXXXNXO0NXXKKXXXXX\r\n" + 
				"XXXXXKKXXXOOXXXXXXXXXXXKkoo0NNOd0NKl... ......,kXXXXk,..........lKN0dONX0ookKNXXXXXXXXXXOOXXXKKXXXXX\r\n" + 
				"XXXXXKXNXXO0NXXXXXXXXNKxkkxKNXkxX0c..........;ONXXNXXO;..........c0XxxXNKxkkxKNXXXXNXXXN0kKNXXKXXXXX\r\n" + 
				"XXXXXKXNXKk0NXXXXXXXX0xkXkxXNXxk0:... ......;ONXXXNXXNO;..........;0kxXNXxkXkx0XXXXXXXXN0kKNXXKXXXXX\r\n" + 
				"XXXXXKXXXKk0NXXXXXXX0dOXNkxXNXxl,..........cdxKXXXXXNKkdc. ........,lxXNXxkXXOx0XXXXXXXN0kKNXXKXNXXX\r\n" + 
				"XXXXXKKXXXOOXXXXXXXOdOXXNOdKNXd. ....... .lKXkxKXXXNKxkXKo...........dXNKdONXX0dOXXXXXXXOOXXXKKXXXXX\r\n" + 
				"XXXXXKKXXXOOXXXXXXkx0XXXNKxkXd'..........dXXXXkxKNX0xkXXXXd... .......dXOxKNXXX0xOXXXXXXOOXXXKKXXXXX\r\n" + 
				"XXXXXKKXXX0kKXXXXkxKXXXXXXOdc.   .   ..'xXXXXXXOxkkxOXXXXXXx' .  ..   .ldOXXXXXX0dkXXXXKk0XXXKKXXXXX\r\n" + 
				"XXXXXK0KKK0kkOOkookOOOOOOOx:,:ccc,,cc;.'::::::::,'',::::::::'.;cc,,ccc:,:xOOOOOOOkookOOxx0KKK0KXXXXX\r\n" + 
				"XXXXXXKKXXN0kKKxkXNXXXNXNKdkkxKNN0xkk;.. ..  . .ckkc.  ... ...;kkx0NNKxkkx0NXXXXXNXkxKKk0NNXKKXXXXXX\r\n" + 
				"XXXXXXXKXXXXOkxOXXXXXXXX0xOXXOxOXNKo......... .lKNNKl. .........dXNXOxOXXOx0XXXXXXXXOxkOXXNKKXXXXXXX\r\n" + 
				"XXXXXXXKKXXX0dxXXXXXXXXOd0XXXX0xx0x'..........oKXXXXKo..........'x0kk0XXXX0dOXXXXXXXXxd0NXXKKNXXXXXX\r\n" + 
				"XXXXXXXXKKXK00OOXXXXXXkx0NXXXXXXOc...........ckOOOOOOkc...........cOXXXXXXN0xkXXXXXXOk00KXKKXXXXXXXX\r\n" + 
				"XXXXXXXXXK00KNXOOXXXXkxKXXXXXXXKo... ......'d0OOOOOOOO0x'..........oKXXXXXXXKxkXXXXOOXXK00KXXXXXXXXX\r\n" + 
				"XXXXXXXXXX0KXXXXOkKXkxKNXXXXXXKc.... ......o0KKXXXXXXKK0o...........cKNXXXXXNKxxKKOOXXXXK0KXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXKKXXXX0kdkXNXXXXXX0:..........;kOOOOOOOOOOOOOOk;..........:0XXXXXXXXkdk0XXXXKKXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXKKXXKOkOKXXXXXNO;..........c0NNNNNNNNNNNNNNNN0c..........;OXNNXXX0OkOXNXKKXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXKKKKOOKOxkOOOOx;..........;xOOOOOOOOOOOOOOOOOOx;..........:xO0OOkxOK0OK0KKXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXK00KKKK0kxxddkOOOOOOOkloO0OOO00O000OOOOOO00O0OolkOOOOOOOkddxxk0KKKK00KXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXKKXXXXKxxO0KXXXXNKxxXXXXXXXXXXXXXXXXXXXXXXNXxxKXXXXXK0kdkKNXXXKKXXKXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXKKXX00XK0OO0KXKxkXXXXXXXXXXXXXXXXXXXXXXXXNXkxKXK0OO0KX00XXKKKXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXK00KXXNXK00kdx0KXXXNNXXXXXXXXXXXXXNNNXXXK0xdO00KXXXXK00KXNXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXKKKXXXXKO0K00000000000KKKKK000000000000K0OKNXXKKKKXKXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKK0KXXXNXXXKK00000000000000KKXXXNXXXK0KKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXNXKKKKKKKKKXXXXXXXNNNNNNNXXXXXXXXXKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXKKKKKKKKKKKKKKKKKKKKKKKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX\r\n" + 
				"");
		
		//print the "Star Wars" logo
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMWNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXWMMWNXXXXXXXXXXNWMMMMMWNXXXXXXXXXXXXXXNWMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMWOl,..............................,OMNo'..........;0MMMMMO,..............';lkNMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMWk.                                .kWk.            :XMMMMx.                  ;OWMMMMMMMMM\r\n" + 
				"MMMMMMMMMMNc                                 .kK;       .     .dWMMMx.       '''''.      ,0MMMMMMMMM\r\n" + 
				"MMMMMMMMMMWd.       .:dddddddddc.      :dddddk0l       cd.     .OMMMx.      ;KNWWNXc     .kMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMXl.       ,xXMMMMMMM0'     .xMMMMMMk.      ,KWo      :XMMx.      'xOOOOx;     ,0MMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMNx'        'xNMMMMM0'     .xMMMMMK;      .kWMX:     .oWMx.                 .:OWMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMXd'       .lXMMMM0'     .xMMMMNl       ;xOOOc.     .OMx.              .cd0WMMMMMMMMMMM\r\n" + 
				"MMNOkkkkkkkkkkkxl.        oWMMM0'     .xMMMMk.                    :Xx.      ..      .lxkkkkkkkkkkXMM\r\n" + 
				"MMk.                      ;XMMM0'     .xMMMK;        ......       .od.      ;Od'                .oWM\r\n" + 
				"MMk.                     .dWMMM0'     .xMMNo        :OKKKK0l.      .;.      ;XMXo.               oWM\r\n" + 
				"MMO,...................'ckNMMMMK:.....'kMM0;.......:KMMMMMMXl...............cXMMWKo'.............dWM\r\n" + 
				"MM0l;;;;;lOKKKOl;;;;;cONMMXxoool:lkKKkllooc:;;;;ckKXWMMMNkooc;;;;;;;;;;;:lxOXWMMMMXxc;;;;;;;;;;;:OWM\r\n" + 
				"MM0,     .dWMWx.      lNMWo      :XMNc           c0XMMMM0'                .,dXMMWk'              oWM\r\n" + 
				"MMWd.     '0MX;       .kWK,     .xWWx.           .'dWMMM0'                   ;KMO'               oWM\r\n" + 
				"MMMX:      cXd.        ;Kx.     :XMK,     .;.      '0MMM0'      .cdxxdd;      oWO.        ..'''',kWM\r\n" + 
				"MMMMk.     .c,          :,     .xMNl      lXo       cXMM0'      'OMMWWWk.     oWNc        ,kXNNNNWMM\r\n" + 
				"MMMMNl                         :XWx.     ;KMK;      .dWM0'       ':;:;;.     ;KMMXo.       .c0WMMMMM\r\n" + 
				"MMMMMK,                       .xMK,     .kWMWk.      'OM0'               ..:xXMMMMWO:.       .oNMMMM\r\n" + 
				"MMMMMWx.          ,.          :XNl      .;:::,.       :X0'              .lKWWWWWWWWWNk,        lNMMM\r\n" + 
				"MMMMMMXc         'Od.        .xWk.                    .dO'      .c;      .,;;;;;;;;,;,.        .kMMM\r\n" + 
				"MMMMMMMO.        oWX;        :XK,      .;ccccc,        'l'      '0Nk,                          .kMMM\r\n" + 
				"MMMMMMMWo       '0MMk.      .kNl       lNMMMMMX:        ..      '0MMNx,                       .dNMMM\r\n" + 
				"MMMMMMMMXdclllclkWMMNklcclccxNNxcccclcdXMMMMMMMKoccllllllllccclldXMMMMXxllcllllcccccccccclllokXWMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"\r\n" + 
				"");
		
	}

}
